version: '3'
services:
  uas_api:
    build: ./php
    image: laravel:latest
    container_name: uas_api
    hostname: "uas_api"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on: 
      - db_uas

  db_uas:
    image: mariadb:10.2
    container_name: db_uas
    restart: unless-stopped
    tty: true
    ports:
      - "63306:3306"
    volumes:
      - ./database/data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_DATABASE: your_database
      MYSQL_USER: droid
      MYSQL_PASSWORD: roid1234
      MYSQL_ROOT_PASSWORD: roid12345
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  nginx_uas_api:
    build: ./nginx
    image: nginx_uas_api:latest
    container_name: nginx_uas_api
    hostname: "nginx_uas_api"
    ports:
      - "83:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - uas_api
